apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todolist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mnov34-for-eni/project-devops-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todolist
spec:
  ports:
    - port: 80
  selector:
    app: frontend